context:
  version: "0.2.0"
  mojo_version: ">=1.0.0,<1.1.0"
  max_core_version: ">=26.5.0,<26.6"

package:
  name: "scijo"
  version: ${{ version }}

source:
  - git: https://github.com/mojomath/SciJo.git
    rev: 515fb2856f0ecf3d2740a34d958fe168183e1129

build:
  number: 0
  script:
      - mkdir -p ${{ PREFIX }}/lib/mojo
      - mojo precompile -I ${{ PREFIX }}/lib/mojo scijo -o ${{ PREFIX }}/lib/mojo/scijo.mojoc

requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
    - max-core ${{ max_core_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}
    - max-core ${{ max_core_version }}

about:
  homepage: https://github.com/mojomath/SciJo.git
  license: Apache-2.0
  license_file: LICENSE
  summary: SciJo is a high-performance scientific computing library written in Mojo🔥, inspired by SciPy.
  repository: https://github.com/mojomath/SciJo

extra:
  project_name: SciJo
  maintainers:
    - shivasankarka
