context:
  version: "0.2.0"
  mojo_version: ">=1.0.0,<1.1.0"
  numojo_version: "==0.10.0"
  msl_version: "==0.2.0"

package:
  name: "scijo"
  version: ${{ version }}

source:
  - git: https://github.com/mojomath/SciJo.git
    rev: 4e23949e34ec9fed4e1430c762b55936931dc33d

build:
  number: 0
  script:
      - mkdir -p ${{ PREFIX }}/lib/mojo
      - mojo precompile -I ${{ PREFIX }}/lib/mojo scijo -o ${{ PREFIX }}/lib/mojo/scijo.mojoc

requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
    - numojo ${{ numojo_version }}
    - msl ${{ msl_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}
    - numojo ${{ numojo_version }}
    - msl ${{ msl_version }}

about:
  homepage: https://github.com/mojomath/SciJo
  license: Apache-2.0
  license_file: LICENSE
  summary: SciJo is a high-performance scientific computing library written in Mojo🔥, inspired by SciPy.
  repository: https://github.com/mojomath/SciJo

extra:
  project_name: SciJo
  maintainers:
    - shivasankarka
