context:
  version: "0.9.0"
  mojo_version: "=0.26.2"

package:
  name: "numojo"
  version: ${{ version }}

source:
  - git: https://github.com/Mojo-Numerics-and-Algorithms-group/NuMojo.git
    rev: d4b7fd744a81c855bd99905b2a42bf05cbd705a2

build:
  number: 0
  script:
    - mojo package numojo -o ${{ PREFIX }}/lib/mojo/numojo.mojopkg

requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}

about:
  homepage: https://github.com/Mojo-Numerics-and-Algorithms-group/NuMojo
  license: Apache-2.0
  license_file: LICENSE
  summary: NuMojo is a library for numerical computing in Mojo 🔥 similar to NumPy, SciPy in Python.
  repository: https://github.com/Mojo-Numerics-and-Algorithms-group/NuMojo

extra:
  project_name: NuMojo
  maintainers:
    - shivasankarka
    - MadAlex1997
    - forFudan
    - sandstromviktor
