context:
  version: "0.16.0"
  max_version: "=25.4"

package:
  name: "extramojo"
  version: ${{ version }}

source:
  - git: https://github.com/ExtraMojo/ExtraMojo.git
    rev: 75b80da6249467b9df8f16fa432814b987504126
  # path: .
  # use_gitignore: true

build:
  number: 0
  script:
    - mojo package ExtraMojo -o ${{ PREFIX }}/lib/mojo/ExtraMojo.mojopkg
requirements:
  host:
    - max ${{ max_version }}
  run:
    - max ${{ max_version }}

tests:
  - script:
      - if: unix
        then:
          - mojo run -I ${{ PREFIX }}/lib/mojo/ExtraMojo.mojopkg tests/test_file.mojo
          - mojo test -I ${{ PREFIX }}/lib/mojo/ExtraMojo.mojopkg tests
    requirements:
      run:
        - max ${{ max_version }}
    files:
      source:
        - tests/

about:
  homepage: https://github.com/ExtraMojo/ExtraMojo
  license: "Unlicense OR MIT"
  license_file:
    - LICENSE-MIT
    - UNLICENSE
  summary: Extra functionality not yet in the standard library, mostly focused on strings and file IO.
  repository: https://github.com/ExtraMojo/ExtraMojo

extra:
  maintainers:
    - sstadick
  project_name: extramojo
