context:
  version: "0.18.0"
  mojo_version: "=0.25.6"

package:
  name: "extramojo"
  version: ${{ version }}

source:
  - git: https://github.com/ExtraMojo/ExtraMojo.git
    rev: 01b09557f73fb3a1a64bf48d3ef39fa826b24703
  # path: .
  # use_gitignore: true

build:
  number: 0
  script:
    - mojo package extramojo -o ${{ PREFIX }}/lib/mojo/extramojo.mojopkg
requirements:
  build:
    - mojo-compiler ${{ mojo_version }}
  host:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}

tests:
  - script:
      - if: unix
        then:
          - mojo run -I . tests/test_file.mojo
          - mojo test -I . tests
    requirements:
      build:
        - mojo ${{ mojo_version }}
      run:
        - mojo ${{ mojo_version }}
    files:
      source:
        - extramojo/
        - tests/

about:
  homepage: https://github.com/ExtraMojo/ExtraMojo
  license: "Unlicense OR MIT"
  license_file:
    - LICENSE-MIT
    - UNLICENSE
  summary: Extra functionality not yet in the standard library, mostly focused on strings and file IO.
  repository: https://github.com/ExtraMojo/ExtraMojo

extra:
  maintainers:
    - sstadick
  project_name: extramojo
