about:
  description: "# Mojo Regex\nRegular Expressions Library for Mojo\n\n`regex` is a\
    \ regex library featuring a hybrid DFA/NFA engine architecture that automatically\
    \ optimizes pattern matching based on complexity.\n\nIt aims to provide a similar\
    \ interface as the [re](https://docs.python.org/3/library/re.html) stdlib package\
    \ while leveraging Mojo's performance capabilities."
  homepage: https://github.com/msaelices/mojo-regex
  license: MIT
  license_file: LICENSE
  repository: https://github.com/msaelices/mojo-regex
  summary: Library for dealing with regular expressions in Mojo
build:
  number: 0
  script:
  - mkdir -p ${PREFIX}/lib/mojo
  - pixi run mojo package src/regex -o ${PREFIX}/lib/mojo/regex.mojopkg
context:
  version: 13.4.2
package:
  name: regex
  version: 0.1.0
requirements:
  run:
  - max >= 25.4.0
source:
  - git: https://github.com/msaelices/mojo-regex.git
    rev: 25f2f6c7e7399098302ab04752d790fd9093d263
