context:
  version: "0.2.0"
  mojo_version: "==1.0.0"
  max_core_version: "==26.5.0"

package:
  name: "mojoblas"
  version: ${{ version }}

source:
  - git: https://github.com/shivasankarka/mojoBLAS.git
    rev: 09ad6aa9a24847b7e44bcf81dadf00994f5fe80a

build:
  number: 0
  script:
    - mkdir -p ${{ PREFIX }}/lib/mojo
    - mojo precompile -I ${{ PREFIX }}/lib/mojo mojoblas -o ${{ PREFIX }}/lib/mojo/mojoblas.mojoc

requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
    - max-core ${{ max_core_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}
    - max-core ${{ max_core_version }}

about:
  homepage: https://github.com/shivasankarka/mojoBLAS
  license: MIT
  license_file: LICENSE
  summary: mojoBLAS is a high performance Mojo implementation of BLAS (Basic Linear Algebra Subprograms) routines.
  repository: https://github.com/shivasankarka/mojoBLAS.git

extra:
  project_name: mojoblas
  maintainers:
    - shivasankarka
