context:
  version: "0.9.0"
  mojo_version: ">=1.1.0, <1.2.0"

package:
  name: "argmojo"
  version: ${{ version }}

source:
  - git: https://github.com/forfudan/argmojo.git
    rev: 1d0054987cb47136cdf16d64cfe7db3fcdfefc97

build:
  number: 0
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo precompile src/argmojo -o ${{ PREFIX }}/lib/mojo/argmojo.mojoc

requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}

about:
  homepage: https://github.com/forfudan/argmojo
  license: Apache-2.0
  license_file: LICENSE
  summary: A feature-rich command-line argument parser library for Mojo, with both builder and struct-based declarative APIs.
  repository: https://github.com/forfudan/argmojo.git

extra:
  project_name: argmojo
  maintainers:
    - forfudan
