context:
  version: "0.6.0"
  mojo_version: "=1.0.0b1"

package:
  name: "argmojo"
  version: ${{ version }}

source:
  - git: https://github.com/forfudan/argmojo.git
    rev: 47df395940e9f9048a4535c2531aeeedfb40a7ca

build:
  number: 0
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo package src/argmojo -o ${{ PREFIX }}/lib/mojo/argmojo.mojopkg

requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}

about:
  homepage: https://github.com/forfudan/argmojo
  license: Apache-2.0
  license_file: LICENSE
  summary: A feature-rich command-line argument parser library for Mojo, with both builder and struct-based declarative APIs.
  repository: https://github.com/forfudan/argmojo.git

extra:
  project_name: argmojo
  maintainers:
    - forfudan
