context:
  version: "0.4.1"

package:
  name: "decimojo"
  version: ${{ version }}

source:
  - git: https://github.com/forFudan/decimojo.git
    rev: 51c983229749df1caf490ccb9ddea19e7f220441

build:
  number: 0
  script:
    - mojo package src/decimojo -o ${{ PREFIX }}/lib/mojo/decimojo.mojopkg
requirements:
  host:
    - max=25.4
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo run tests.mojo
    requirements:
      run:
        - max=25.4
    files:
      recipe:
        - tests.mojo

about:
  homepage: https://github.com/forFudan/decimojo.git
  license: Apache-2.0
  license_file: LICENSE
  summary: An arbitrary-precision decimal and integer mathematics library for Mojo
  repository: https://github.com/forFudan/decimojo.git

extra:
  project_name: decimojo
  maintainers:
    - forfudan
