context:
  version: 1.6.2
package:
  name: "mojo_csv"
  version: ${{ version }}

source:
  - git: https://github.com/Phelsong/mojo_csv.git
    rev: 8e67c53570d3a9beb7c99e81a40079bc1328e692

build:
  number: 3
  script:
    - mojo package src -o ${{ PREFIX }}/lib/mojo/mojo_csv.mojopkg

requirements:
  host:
    - max >=26.0,<27.0
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo run -I $PREFIX/lib/mojo/mojo_csv.mojopkg test_pack.mojo
    files:
      recipe:
        - test_pack.mojo
    requirements:
      run:
        - max >=26.0,<27.0

about:
  homepage: https://github.com/Phelsong/mojo_csv
  license: MIT
  license_file: LICENSE
  summary: Csv parsing library written in pure Mojo
  repository: https://github.com/Phelsong/mojo_csv

extra:
  maintainers:
    - phelsong
  project_name:
    - mojo_csv
