context:
  version: 1.6.2
package:
  name: "mojo_csv"
  version: ${{ version }}

source:
  - git: https://github.com/Phelsong/mojo_csv.git
    rev: 0ee9ea6f5511efbdf48c64c81fea834f23690579

build:
  number: 1
  script:
    - mojo package src -o ${{ PREFIX }}/lib/mojo/mojo_csv.mojopkg

requirements:
  host:
    - max >=26.0,<27.0
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - export MODULAR_MOJO_IMPORT_PATH="${{ PREFIX }}/lib/mojo"
          - mojo mojo_csv/test_pack.mojo
    files:
      recipe:
        - mojo_csv

about:
  homepage: https://github.com/Phelsong/mojo_csv
  license: MIT
  license_file: LICENSE
  summary: Csv parsing library written in pure Mojo
  repository: https://github.com/Phelsong/mojo_csv

extra:
  maintainers:
    - phelsong
  project_name:
    - mojo_csv
