context:
  version: 1.6.1
package:
  name: "mojo_csv"
  version: ${{ version }}

source:
  - git: https://github.com/Phelsong/mojo_csv.git
    rev: 035a354cb4c1493de3b9dbda49715208dd433075

build:
  number: 0
  script:
    - mojo package src -o ${{ PREFIX }}/lib/mojo/mojo_csv.mojopkg

requirements:
  host:
    - max >=26.0,<27.0
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo tests/mojo_csv/test_pack.mojo
    files:
      recipe:
        - mojo_csv

about:
  homepage: https://github.com/Phelsong/mojo_csv
  license: MIT
  license_file: LICENSE
  summary: Csv parsing library written in pure Mojo
  repository: https://github.com/Phelsong/mojo_csv

extra:
  maintainers:
    - phelsong
  project_name:
    - mojo_csv
