context:
  version: "0.1.1"

package:
  name: "websockets"
  version: ${{ version }}

source:
  - git: https://github.com/msaelices/mojo-websockets.git
    rev: 4835c1ae0cf9d49b77ced42daf9821f62418450c

build:
  number: 0
  script:
    - mojo package src/websockets -o ${PREFIX}/lib/mojo/websockets.mojopkg

requirements:
  host:
    - max == 25.1
  run:
    - ${{ pin_compatible('max') }}

about:
  homepage: https://github.com/msaelices/mojo-websockets
  license: MIT
  license_file: LICENSE
  summary: Mojo's websockets library
  repository: https://github.com/msaelices/mojo-websockets

extra:
  maintainers:
    - msaelices
  project_name: mojo-websockets
