context:
  version: "0.0.1"

package:
  name: "small-time"
  version: ${{ version }}

source:
  - git: https://github.com/thatstoasty/small-time.git
    rev: 54f579686cf56e021b8c02a07868fcca8dbc8d49

build:
  number: 0
  script:
    - mojo package src/small_time -o ${{ PREFIX }}/lib/mojo/small_time.mojopkg
requirements:
  host:
    - max
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo run test.mojo
    files:
      recipe:
        - test.mojo

about:
  homepage: https://github.com/thatstoasty/small-time
  license: Apache-2.0
  license_file: LICENSE
  summary: Datetime library
  repository: https://github.com/thatstoasty/small-time

extra:
  maintainers:
    - Hofer-Julian
