context:
  version: "0.0.1"

package:
  name: "mist"
  version: ${{ version }}

source:
  - git: https://github.com/thatstoasty/mist.git
    rev: 3c07884d8ff5c823859bf4aebf532d8c4042357d

build:
  number: 0
  script:
    - mojo package src/mist -o ${{ PREFIX }}/lib/mojo/mist.mojopkg
requirements:
  host:
    - max =24.6
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo test test

about:
  homepage: https://github.com/thatstoasty/mist
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: MIT
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE
  summary: Mist lets you safely use advanced styling options on the terminal.
  repository: https://github.com/thatstoasty/mist

extra:
  maintainers:
    - thatstoasty
