context:
  version: "0.2.0"
  mojo_version: ">=1.1.0,<1.2.0"
  max_core_version: ">=26.6.0,<26.7"
  decimo_version: ">=0.15.0,<0.16"

package:
  name: "linamo"
  version: ${{ version }}

source:
  - git: https://github.com/mojomath/linamo.git
    rev: 559bbaa4bd04ff66d7a800a349ac0427987cdc78

build:
  number: 0
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo precompile -I ${PREFIX}/lib/mojo src/linamo -o ${PREFIX}/lib/mojo/linamo.mojoc

requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
    - decimo ${{ decimo_version }}
    - max-core ${{ max_core_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}
    - decimo ${{ decimo_version }}
    - max-core ${{ max_core_version }}

about:
  homepage: https://github.com/mojomath/linamo
  license: Apache-2.0
  license_file: LICENSE
  summary: Linear algebra for Mojo, specialized for two-dimensional matrices.
  repository: https://github.com/mojomath/linamo.git

extra:
  project_name: linamo
  maintainers:
    - forfudan
