context:
  version: 0.1.2
  mojo_version: "=25.5"

package:
  name: "kelvin"
  version: ${{ version }}

source:
 - git: https://github.com/bgreni/Kelvin.git
   rev: fcd18cad27aac76daf818782115d06e251ed9f40

build:
  number: 0
  script:
    - mojo package kelvin -o ${{ PREFIX }}/lib/mojo/kelvin.mojopkg

requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - ${{ pin_compatible('mojo-compiler') }}

tests:
  - script:
    - if: unix
      then:
        - mojo test
        # Can't convince PR build to find this file
        # - python3 scripts/run_reject_tests.py
    requirements:
      build:
        - mojo ${{ mojo_version }}
      run:
        - mojo ${{ mojo_version }}

about:
  homepage: https://github.com/bgreni/Kelvin
  license: Apache-2.0
  license_file: LICENSE
  summary: A powerful dimensional analysis library written in Mojo
  repository: https://github.com/bgreni/Kelvin

extra:
  maintainers:
    - bgreni
  project_name:
    - Kelvin