context:
  version: 0.4.0

package:
  name: "emberjson"
  version: ${{ version }}

source:
 - git: https://github.com/bgreni/EmberJson.git
   tag: 0.4.0

build:
  number: 0
  script:
    - mojo precompile emberjson -o ${{ PREFIX }}/lib/mojo/emberjson.mojoc

requirements:
  host:
    - mojo-compiler =1.1.0
    - emberserde =0.1.0
  build:
    - mojo-compiler =1.1.0
    - emberserde =0.1.0
  run:
    - ${{ pin_compatible('mojo-compiler') }}
    - emberserde =0.1.0

tests:
  - script:
    - if: unix
      then:
        - python run_tests.py
    files:
      source:
        - run_tests.py
        - test/
        - emberjson/
        - bench_data/
    requirements:
      build:
        - mojo =1.1.0
        - emberserde =0.1.0
      run:
        - mojo =1.1.0

about:
  homepage: https://github.com/bgreni/EmberJson
  license: Apache-2.0
  license_file: LICENSE
  summary: A lightweight JSON parsing library written in pure Mojo
  repository: https://github.com/bgreni/EmberJson

extra:
  maintainers:
    - bgreni
  project_name:
    - EmberJson
