context:
  version: 0.2.0
  mojo_version: "=0.25.6"

package:
  name: "emberjson"
  version: ${{ version }}

source:
 - git: https://github.com/bgreni/EmberJson.git
   rev: 5a456cc8286753d3fcdc5686f0ec48fe2dcee316

build:
  number: 0
  script:
    - mojo package emberjson -o ${{ PREFIX }}/lib/mojo/emberjson.mojopkg

requirements:
  host:
    - mojo-compiler =0.25.6
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - ${{ pin_compatible('mojo-compiler') }}

tests:
  - script:
    - if: unix
      then:
        - mojo test
    requirements:
      build:
        - mojo ${{ mojo_version }}
      run:
        - mojo ${{ mojo_version }}

about:
  homepage: https://github.com/bgreni/EmberJson
  license: Apache-2.0
  license_file: LICENSE
  summary: A lightweight JSON parsing library written in pure Mojo
  repository: https://github.com/bgreni/EmberJson

extra:
  maintainers:
    - bgreni
  project_name:
    - EmberJson