context:
  version: 0.2.0
  mojo_version: "=0.25.6"

package:
  name: mojo-ini
  version: ${{ version }}

source:
  - git: https://github.com/DataBooth/mojo-ini.git
    tag: v0.2.0

build:
  number: 0
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo package src/ini -o ${PREFIX}/lib/mojo/ini.mojopkg

requirements:
  build:
    - mojo-compiler ${{ mojo_version }}
  host:
    - mojo-compiler ${{ mojo_version }}
  run:
    - ${{ pin_compatible('mojo-compiler') }}

test:
  files:
    source:
      - test_package.mojo
  commands:
    - mojo -I ${PREFIX}/lib/mojo test_package.mojo

about:
  homepage: https://github.com/DataBooth/mojo-ini
  license: MIT
  license_file: LICENSE
  summary: INI parser and writer for Mojo with Python configparser compatibility
  description: |
    mojo-ini provides native INI parsing and writing in Mojo with zero Python dependencies.
    It supports classic INI syntax, multiline values (indented continuation), comments,
    and includes a clean public API: parse(), to_ini(), parse_file(), write_file().
  doc_url: https://github.com/DataBooth/mojo-ini#readme
  dev_url: https://github.com/DataBooth/mojo-ini

extra:
  recipe-maintainers:
    - mjboothaus
