context:
  build_number: 0
  release: 0.1.0-compiler-0.26.2.0
  artifact_sha256: b95bbc01a49af8245363faea68d50d6cc229b7515bf1fc373f8edbcf9c8c14ac

about:
  homepage: https://github.com/martinvuyk/mojo_datetime
  license: Apache-2.0 WITH LLVM-exception
  license_file: LICENSE
  summary: A flexible Mojo datetime library implementation
  repository: https://github.com/martinvuyk/mojo_datetime

extra:
  maintainers:
    - martinvuyk
  project_name:
    - mojo_datetime

source:
  url: https://github.com/martinvuyk/mojo_datetime/releases/download/${{ release }}/mojo_datetime.mojopkg
  sha256: ${{ artifact_sha256 }}

package:
  name: "mojo_datetime"
  version: ${{ release }}

build:
  number: ${{ build_number }}
  script:
    - cp mojo_datetime.mojopkg ${{ PREFIX }}/lib/mojo/

requirements:
  host:
    - mojo-compiler "=0.26.2"
  build:
    - mojo-compiler "=0.26.2"
  run:
    - ${{ pin_compatible('mojo-compiler') }}