# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.1.9"

package:
  name: "lightbug_http"
  version: ${{ version }}

source:
  - git: https://github.com/saviorand/lightbug_http.git
    rev: 9f74fb8041494812b6e7b69229aef23f62f5c11e

build:
  number: 0
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo package lightbug_http -o ${{ PREFIX }}/lib/mojo/lightbug_http.mojopkg

requirements:
  host:
      - max =24.6
  run:
    - ${{ pin_compatible('max') }}
    - small_time == 0.1.6

tests:
  - script:
      - if: unix
        then:
          - magic run test
    requirements:
      run:
        - max =24.6
    files:
      recipe:
        - tests/lightbug_http/io/test_bytes.mojo
        - tests/lightbug_http/test_client.mojo
        - tests/lightbug_http/test_cookie.mojo
        - tests/lightbug_http/test_header.mojo
        - tests/lightbug_http/test_http.mojo
        - tests/lightbug_http/test_net.mojo
        - tests/lightbug_http/test_uri.mojo

about:
  homepage: https://lightbug.site
  license: MIT
  license_file: LICENSE
  summary: Lightbug is a simple and sweet HTTP framework for Mojo
  repository: https://github.com/saviorand/lightbug_http

extra:
  maintainers:
    - saviorand
    - bgreni
    - thatstoasty
  project_name: lightbug_http
