# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.1.6"

package:
  name: "lightbug_http"
  version: ${{ version }}

source:
  - git: https://github.com/saviorand/lightbug_http.git
    rev: ea897f70483bf20ec3f4764308404e11d9271151

build:
  number: 0
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - magic run mojo package . -o ${PREFIX}/lib/mojo/lightbug_http.mojopkg

requirements:
  host:
      - max
  run:
    - ${{ pin_compatible('max') }}
    - small_time == 0.1.3

tests:
  - script:
      - if: unix
        then:
          - magic run test
    files:
      source:
        - tests/lightbug_http/

about:
  homepage: https://lightbug.site
  license: MIT
  license_file: LICENSE
  summary: Lightbug is a simple and sweet HTTP framework for Mojo
  repository: https://github.com/saviorand/lightbug_http

extra:
  maintainers:
    - saviorand
  project_name: lightbug_http
