#
# recipe.yaml
# mosaic
#
# Created by Christian Bator on 03/11/2025
#
# Usage: rattler-build build --recipe recipe.yaml -c https://conda.modular.com/max -c conda-forge
#

context:
  version: "0.0.1"

package:
  name: mosaic
  version: ${{ version }}

source:
  - git: https://github.com/christianbator/mosaic.git
    rev: 6c22e6dad13636e390eeec6e40be99e0687e9536

build:
  number: 4
  script: build/build.sh
  dynamic_linking:
    missing_dso_allowlist:
      - if: osx
        then:
          - /usr/lib/swift/libswift*.dylib
          - /usr/lib/libc++*.dylib

requirements:
  build:
    - clang==20.1.4
    - lld==20.1.4
  host:
    - max==25.4.0
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script: |
      cd test
      mojo test
    files:
      source:
        - test/**.mojo
        - test/data/

about:
  homepage: https://mosaiclib.org
  license: Apache-2.0
  license_file: LICENSE
  summary: An open source computer vision library in Mojo
  repository: https://github.com/christianbator/mosaic
  documentation: https://mosaiclib.org/docs

extra:
  project_name: Mosaic
  maintainers:
    - christianbator
