context:
  version: "24.6.0"

package:
  name: "endia"
  version: ${{ version }}

source:
  - git: https://github.com/endia-ai/Endia.git
    rev: 6b5a1a9d9d06e0da6c36aa8c940f45cede424396

build:
  number: 0
  script:
    - mojo package endia -o ${{ PREFIX }}/lib/mojo/endia.mojopkg

requirements:
  host:
    - max
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo run test.mojo
    files:
      recipe:
        - test.mojo

about:
  homepage: https://endia.vercel.app/
  license: Apache-2.0 with LLVM Exceptions
  license_file: LICENSE
  summary: Dynamic Neural Networks in Mojo
  repository: https://github.com/endia-ai/Endia
  description: |
    Endia is a dynamic Machine Learning Library that features algorithmic differentiation
    for computing derivatives of arbitrary order, signal processing capabilities including
    Complex Numbers and Fourier Transforms, JIT compilation via the MAX Engine, and both
    PyTorch-like imperative and JAX-like functional interfaces.
  doc_url: https://endia.vercel.app
  dev_url: https://github.com/endia-ai/Endia

extra:
  maintainers:
    - TilliFe
  project_name: Endia