context:
  version: "0.0.4"
  mojo_version: "=0.25.7"

package:
  name: "opengl-mojo"
  version: ${{ version }}

source:
  - git: https://github.com/ssslakter/opengl-mojo.git
    rev: a33040b26b17e6d0d85e395417c8b594bba3c7a8

build:
  number: 0
  script:
    - mojo package src -o ${{ PREFIX }}/lib/mojo/opengl.mojopkg
requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - ${{ pin_compatible('mojo-compiler') }}

about:
  homepage: https://github.com/ssslakter/opengl-mojo
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenGL bindings for Mojo
  repository: https://github.com/ssslakter/opengl-mojo

extra:
  maintainers:
    - ssslakter
