context:
  version: "0.0.3"

package:
  name: "mojmelo"
  version: ${{ version }}

source:
  - git: https://github.com/yetalit/mojmelo.git
    rev: 9531118fb9df74c3b376befe30da82281f24375f

build:
  number: 0
  script:
    - mojo package magic/mojmelo/utils/mojmelo_matmul -o ${{ PREFIX }}/lib/mojo/mojmelo_matmul.mojopkg
    - mojo package magic/mojmelo -o ${{ PREFIX }}/lib/mojo/mojmelo.mojopkg
requirements:
  host:
    - max =24.6
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo tests/setup.mojo
    requirements:
      run:
        - max =24.6
    files:
      recipe:
        - tests/setup.mojo
        - tests/setup.sh
        - tests/mojmelo/__init__.mojo
        - tests/mojmelo/utils/*.mojo
        - tests/mojmelo/utils/mojmelo_matmul/*.mojo

about:
  homepage: https://github.com/yetalit/Mojmelo
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Machine Learning algorithms in pure Mojo.
  repository: https://github.com/yetalit/Mojmelo

extra:
  project_name: Mojmelo
  maintainers:
    - yetalit
