context:
  version: "0.0.8"

package:
  name: "mojmelo"
  version: ${{ version }}

source:
  - git: https://github.com/yetalit/mojmelo.git
    rev: 04f2b8b4c2a8e495b8e05ad7d7554e1b644df66d

build:
  number: 0
  script:
    - mojo package pixi/mojmelo/utils/mojmelo_matmul -o ${{ PREFIX }}/lib/mojo/mojmelo_matmul.mojopkg
    - mojo package pixi/mojmelo -o ${{ PREFIX }}/lib/mojo/mojmelo.mojopkg
requirements:
  host:
    - max =25.5
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo tests/setup.mojo
    requirements:
      run:
        - max =25.5
    files:
      recipe:
        - tests/setup.mojo
        - tests/setup.sh
        - tests/mojmelo/__init__.mojo
        - tests/mojmelo/utils/*.mojo
        - tests/mojmelo/utils/mojmelo_matmul/*.mojo

about:
  homepage: https://github.com/yetalit/Mojmelo
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Machine Learning algorithms in pure Mojo.
  repository: https://github.com/yetalit/Mojmelo

extra:
  project_name: Mojmelo
  maintainers:
    - yetalit
