context:
  version: "24.6.0"

package:
  name: "max-cv"
  version: ${{ version }}

source:
  - git: https://github.com/BradLarson/max-cv.git
    rev: 21bbd57404548de3c471ec8492dfcc01b76ae457

build:
  number: 0
  noarch: python
  # script: pip install . -v

requirements:
  host:
    - max =24.6
    - python >=3.9,<3.13
  run:
    - ${{ pin_compatible('max') }}
    - python >=3.9,<3.13

tests:
  - script:
      - if: unix
        then:
          - magic run test
    requirements:
      run:
        - max =24.6
        - python >=3.9,<3.13
        - pytest
    files:
      recipe:
        - tests/conftest.py

about:
  homepage: https://github.com/BradLarson/max-cv
  license: Apache-2.0
  license_file: LICENSE
  summary: An image processing framework built upon MAX
  repository: https://github.com/BradLarson/max-cv

extra:
  maintainers:
    - BradLarson
