context:
  version: 0.0.1

package:
  name: "max-cv"
  version: ${{ version }}

source:
 - git: https://github.com/BradLarson/max-cv.git
   rev: 89c15b266a77ab9edae3646708f4615a6a39682a

# build:
#   number: 0
#   script: python -m pip install .

build:
  noarch: python
  script: pip install . -v

requirements:
  host:
    - python
    - pip
    - max=25.4
  run:
    - python
    - ${{ pin_compatible('max') }}

tests:
  - script:
    - if: unix
      then:
        - pixi run test
    requirements:
      run:
        - max =25.4
        - python >=3.9,<3.13
        - pytest

about:
  homepage: https://github.com/bradLarson/max-cv
  license: Apache-2.0
  license_file: LICENSE
  summary: An image processing framework built upon MAX
  repository: https://github.com/bradLarson/max-cv

extra:
  maintainers:
    - BradLarson
  project_name:
    - MAX-CV
