context:
  version: 0.0.1

package:
  name: max-cv
  version: ${{ version }}

source:
 - git: https://github.com/BradLarson/max-cv.git
   rev: 89c15b266a77ab9edae3646708f4615a6a39682a

# build:
#   number: 0
#   script: python -m pip install .

build:
  number: 0
  noarch: python
  script: pip install . -v

requirements:
  host:
    - python
    - pip
    - setuptools
    - max=25.4
    - wheel
  run:
    - python
    - ${{ pin_compatible('max') }}

# tests:
#   - script:
#     - if: unix
#       then:
#         - pixi run test
#     requirements:
#       run:
#         - pytest
#         - max =25.4
#         - python >=3.9,<3.13

# tests:
#   - python:
#       # The Python test type will simply import packages as a sanity check.
#       imports:
#         - rattler
#         - rattler.version.Version
#       pip_check: true 
#       # You can select different Python versions to test against.
      python_version: ["${{ python_min ~ '.*' }}", "3.12.*"]  

 - script:
      - pytest ./tests
    requirements:  
      run:
         - pytest
    files:  
      source:
        - tests/
# tests:
#   - python:
#       imports:
#         - pytest

#   - script:
#     - pixi run test
#     - pytest

# tests:
  # - python
  #   imports:
  #     - numpy
  #     - pathlib
  #     - pytest
  #   requires:
  #     - pip
  #     - python
  #     - pytest
  #   commands:
  #     - pytest ./tests
  #   source_files:
  #     - tests/

about:
  homepage: https://github.com/bradLarson/max-cv
  license: Apache-2.0
  license_file: LICENSE
  summary: An image processing framework built upon MAX
  repository: https://github.com/bradLarson/max-cv

extra:
  maintainers:
    - BradLarson
  project_name:
    - MAX-CV
