name: Remove Incompatible Packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *" # 9 AM PST

permissions:
  contents: write
  pull-requests: write

jobs:
  check-incompatible-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 2
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          pixi-version: v0.63.2

      - name: Configure git
        run: pixi run configure-git

      - name: Run compatibility check script
        run: pixi run remove-incompatible-packages
        env:
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
